# Stubs for falcon.media.base (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class BaseHandler:
    def serialize(self, obj: Any) -> None: ...
    def deserialize(self, raw: Any) -> None: ...
