# Stubs for falcon.media.handlers (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from six.moves import UserDict
from typing import Any, Optional

class Handlers(UserDict):
    def __init__(self, initial: Optional[Any] = ...) -> None: ...
    def find_by_media_type(self, media_type: Any, default: Any): ...
