# Stubs for falcon.media.json (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from falcon.media import BaseHandler
from typing import Any

class JSONHandler(BaseHandler):
    def deserialize(self, raw: Any): ...
    def serialize(self, media: Any): ...
