# Stubs for falcon.routing (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from falcon.routing.converters import *
from falcon.routing.compiled import CompiledRouter

DefaultRouter = CompiledRouter
