# Stubs for falcon.routing.static (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class StaticRoute:
    def __init__(self, prefix: Any, directory: Any, downloadable: bool = ...) -> None: ...
    def match(self, path: Any): ...
    def __call__(self, req: Any, resp: Any) -> None: ...
