# Stubs for falcon.testing.helpers (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from falcon.util import http_now
from typing import Any, Optional

DEFAULT_HOST: str
httpnow = http_now

def get_encoding_from_headers(headers: Any): ...
def rand_string(min: Any, max: Any): ...
def create_environ(path: str = ..., query_string: str = ..., protocol: str = ..., scheme: str = ..., host: Any = ..., port: Optional[Any] = ..., headers: Optional[Any] = ..., app: str = ..., body: str = ..., method: str = ..., wsgierrors: Optional[Any] = ..., file_wrapper: Optional[Any] = ...): ...
def redirected(stdout: Any = ..., stderr: Any = ...) -> None: ...
