# Stubs for falcon (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# from .constants import *
# from .status_codes import *
# from .errors import *
# from .redirects import *
# from .util import *

from .request import (
    Request as Request
)

from .response import (
    Response as Response
)

from .status_codes import *
from .hooks import *
