# Stubs for falcon.constants (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

HTTP_METHODS: Any
WEBDAV_METHODS: Any
COMBINED_METHODS: Any
MEDIA_JSON: str
MEDIA_MSGPACK: str
MEDIA_YAML: str
MEDIA_XML: str
MEDIA_JS: str
MEDIA_HTML: str
MEDIA_TEXT: str
MEDIA_JPEG: str
MEDIA_PNG: str
MEDIA_GIF: str
DEFAULT_MEDIA_TYPE = MEDIA_JSON
