# Stubs for falcon.hooks (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def before(action: Any, *args: Any, **kwargs: Any): ...
def after(action: Any, *args: Any, **kwargs: Any): ...
