# Stubs for falcon.redirects (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from falcon.http_status import HTTPStatus
from typing import Any

class HTTPMovedPermanently(HTTPStatus):
    def __init__(self, location: Any) -> None: ...

class HTTPFound(HTTPStatus):
    def __init__(self, location: Any) -> None: ...

class HTTPSeeOther(HTTPStatus):
    def __init__(self, location: Any) -> None: ...

class HTTPTemporaryRedirect(HTTPStatus):
    def __init__(self, location: Any) -> None: ...

class HTTPPermanentRedirect(HTTPStatus):
    def __init__(self, location: Any) -> None: ...
