"""create user_phrase table

Revision ID: be973e0dbef4
Revises: f8dfc7d72164
Create Date: 2016-08-18 17:34:04.142543

"""

# revision identifiers, used by Alembic.
revision = 'be973e0dbef4'
down_revision = 'f8dfc7d72164'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_phrase',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeats', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('progress <= repeats'),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrase.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'phrase_id')
    )
    op.create_index(op.f('ix_user_phrase_completion_time'), 'user_phrase', ['completion_time'], unique=False)
    op.create_index(op.f('ix_user_phrase_phrase_id'), 'user_phrase', ['phrase_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phrase_phrase_id'), table_name='user_phrase')
    op.drop_index(op.f('ix_user_phrase_completion_time'), table_name='user_phrase')
    op.drop_table('user_phrase')
    ### end Alembic commands ###
