"""add column added_by_user_id

Revision ID: e75876149b04
Revises: be973e0dbef4
Create Date: 2016-08-25 16:40:45.322350

"""

# revision identifiers, used by Alembic.
revision = 'e75876149b04'
down_revision = 'be973e0dbef4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_phrase_added_by_user_id'), 'phrase', ['added_by_user_id'], unique=False)
    op.create_foreign_key(None, 'phrase', 'phrase', ['added_by_user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phrase', type_='foreignkey')
    op.drop_index(op.f('ix_phrase_added_by_user_id'), table_name='phrase')
    op.drop_column('phrase', 'added_by_user_id')
    ### end Alembic commands ###
