"""create tables needed for dictionary

Revision ID: f8dfc7d72164
Revises: c373991c14f4
Create Date: 2016-08-18 11:05:32.079749

"""

# revision identifiers, used by Alembic.
revision = 'f8dfc7d72164'
down_revision = 'c373991c14f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.Enum('en', 'ru', name='language'), nullable=False),
    sa.Column('target_lang', sa.Enum('en', 'ru', name='language'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_section_phrase',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrase.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['grammar_section.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'phrase_id')
    )
    op.create_index(op.f('ix_grammar_section_phrase_phrase_id'), 'grammar_section_phrase', ['phrase_id'], unique=False)
    op.create_table('theme_phrase',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrase.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('theme_id', 'phrase_id')
    )
    op.create_index(op.f('ix_theme_phrase_phrase_id'), 'theme_phrase', ['phrase_id'], unique=False)

    op.rename_table('users', 'user')
    op.execute('ALTER SEQUENCE users_id_seq RENAME TO user_id_seq')
    op.execute('ALTER INDEX users_pkey RENAME TO user_pkey')
    op.execute('ALTER INDEX users_email_key RENAME TO user_email_key')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_phrase_phrase_id'), table_name='theme_phrase')
    op.drop_table('theme_phrase')
    op.drop_index(op.f('ix_grammar_section_phrase_phrase_id'), table_name='grammar_section_phrase')
    op.drop_table('grammar_section_phrase')
    op.drop_table('theme')
    op.drop_table('phrase')
    op.drop_table('grammar_section')

    op.rename_table('user', 'users')
    op.execute('ALTER SEQUENCE user_id_seq RENAME TO users_id_seq')
    op.execute('ALTER INDEX user_pkey RENAME TO users_pkey')
    op.execute('ALTER INDEX user_email_key RENAME TO users_email_key')
    op.execute('DROP TYPE language')

    ### end Alembic commands ###
