db:
    url: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
    echo: false
redis:
    host: redis
    port: 6379
    db: 0
session:
    duration-seconds: 3600
    secure: false
dictionary:
    limit: 15
my-dictionary:
    datetime-format: "%Y-%m-%d %H:%M"
default-profile:
    auto-speak: true
    speak-language: en

    working-set-size: 10
    repeats: 5
    completed-repeat-factor: 0.35

