db:
    url: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
    echo: false
redis:
    host: redis
    port: 6379
    db: 0
session:
    duration_seconds: 604800
    secure: false
dictionary:
    limit: 15
my_dictionary:
    datetime_format: "%Y-%m-%d %H:%M"
default_profile:
    training_type: typing
    auto_speak: true
    speak_language: en

    working_set_size: 10
    repeats: 5
    completed_repeat_factor: 0.35

