version: '2'
# use "docker-compose exec" to run a command in a running service
services:
    wsgi_app:
        container_name: wsgi_app
        image: lopalo/drill-backend
        depends_on:
            - postgres
            - redis
        volumes:
            - "..:/drill"
        command: uwsgi --yaml /drill/configs/uwsgi.yaml
    nginx:
        container_name: nginx
        image: nginx:1.10.1
        depends_on:
            - wsgi_app
        volumes:
            - "..:/drill"
        ports:
            - "80:80"
        command: nginx -c /drill/configs/nginx.conf
    postgres:
        container_name: postgres
        image: postgres:9.5.3
        volumes:
            - "../db:/var/lib/postgresql/data"
            - "./postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
            - "../logs:/var/lib/postgresql/data/logs"
        # for making dumps
        # ports:
        #     - "127.0.0.1:5432:5432"
    redis:
        container_name: redis
        image: redis:3.2.3
        volumes:
            - "./redis.conf:/data/redis.conf"
            - "../logs:/data/logs"
        command: redis-server /data/redis.conf

