# Stubs for falcon.util (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from falcon.util.misc import *
from falcon.util.time import *
from typing import Any

CaseInsensitiveDict: Any
